name: $(Build.SourceBranchName)$(Rev:.r)

variables:
  ES_VERSION: 7.3.2
  JDK_VERSION: 11

jobs:
# --------------------------------------------------
- job: build_image_ltsc2016
  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - template: build-image-template.yaml
    parameters:
      WIN_VERSION: 'windowsservercore-ltsc2016'

# --------------------------------------------------
- job: build_image_1803
  condition: succeeded()
  pool:
    vmImage: 'win1803'

  steps:
  - template: build-image-template.yaml
    parameters:
      WIN_VERSION: 'windowsservercore-1803'

# --------------------------------------------------
- job: build_image_1809
  condition: succeeded()
  pool:
    vmImage: 'windows-2019'

  steps:
  - template: build-image-template.yaml
    parameters:
      WIN_VERSION: 'windowsservercore-1809'
