name: $(Build.SourceBranchName)$(Rev:.r)

#https://www.elastic.co/support/matrix#matrix_jvm
variables:
  ES_VERSION: 7.5.0
  JDK_VERSION: 13

jobs:
# ------- Package ---------------------------------------------------------
- job: manifest
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: Docker@2
    displayName: login on docker hub
    inputs:
      command: login
      containerRegistry: docker-hub-gigi81

  - bash: |
     mkdir -p ~/.docker
     echo '{ "experimental": "enabled" }' > ~/.docker/config.json
     docker --config ~/.docker manifest create gigi81/elasticsearch-windows:${ES_VERSION} \
                                               gigi81/elasticsearch-windows:${ES_VERSION}-windowsservercore-ltsc2016 \
                                               gigi81/elasticsearch-windows:${ES_VERSION}-windowsservercore-1803 \
                                               gigi81/elasticsearch-windows:${ES_VERSION}-windowsservercore-1809
    displayName: 'create manifest'

  - task: Docker@2
    displayName: publish manifest
    inputs:
      command: push
      repository: gigi81/elasticsearch-windows
      tags: $(ES_VERSION)
