name: $(ES_VERSION)$(Rev:.r)

variables:
  #https://www.elastic.co/downloads/past-releases#elasticsearch
  ES_VERSION: 2.4.5
  #https://www.elastic.co/support/matrix#matrix_jvm
  #https://hub.docker.com/_/openjdk
  JDK_VERSION: 8u212-b04

jobs:
# --------------------------------------------------
- job: build_image_ltsc2016
  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - template: build-image-template.yaml
    parameters:
      WIN_VERSION: 'windowsservercore-ltsc2016'

# --------------------------------------------------
- job: build_image_1803
  condition: succeeded()
  pool:
    vmImage: 'win1803'

  steps:
  - template: build-image-template.yaml
    parameters:
      WIN_VERSION: 'windowsservercore-1803'

# --------------------------------------------------
- job: build_image_1809
  condition: succeeded()
  pool:
    vmImage: 'windows-2019'

  steps:
  - template: build-image-template.yaml
    parameters:
      WIN_VERSION: 'windowsservercore-1809'
