name: $(Build.SourceBranchName)$(Rev:.r)

variables:
  ES_VERSION: 7.2.0
  JDK_VERSION: 11

# --------------------------------------------------
jobs:
- job: build_image_1809
  pool:
    vmImage: 'windows-2019'

  steps:
  - template: build-image-template.yaml
    parameters:
      ES_VERSION: $(ES_VERSION)
      WIN_VERSION: 'windowsservercore-1809'
      JDK_VERSION: $(JDK_VERSION)

# --------------------------------------------------
- job: build_image_1803
  pool:
    vmImage: 'win1803'

  steps:
  - template: build-image-template.yaml
    parameters:
      ES_VERSION: $(ES_VERSION)
      WIN_VERSION: 'windowsservercore-1803'
      JDK_VERSION: $(JDK_VERSION)

# --------------------------------------------------
- job: build_image_ltsc2016
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - template: build-image-template.yaml
    parameters:
      ES_VERSION: $(ES_VERSION)
      WIN_VERSION: 'windowsservercore-ltsc2016'
      JDK_VERSION: $(JDK_VERSION)
